#!/usr/bin/env zsh

# This file contains all of my custom keybindings in zsh

# vim keybindings
bindkey -v

# <C-e> edits current line
autoload -Uz edit-command-line
zle -N edit-command-line
bindkey '^e' edit-command-line

function command_not_found_handler {
	local dim='\e[0;2m' reset='\e[0m'
	printf "${dim}zsh: command not found:${reset} %s\n" "$1"
	echo "$1" >> $HOME/.zsh_command_not_found

	return 127
}
