#!/usr/bin/env zsh

# This file contains initialisation code for terminal
# additions such as starship.

eval "$(mcfly init zsh)"

# eval "$(starship init zsh)"

source /usr/share/zsh-theme-powerlevel10k/powerlevel10k.zsh-theme
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
