format = '${custom.vpn_connected}${custom.vpn_pending}$all'

[package]
# symbol = ' '
symbol = '󰏗'

[custom.vpn_connected]
symbol = "󰌆 "
when = "systemctl is-active --quiet shefvpn && ip link show ppp0"
style = "fg:2" # Green

[custom.vpn_pending]
symbol = "󰷖 "
when = "systemctl is-active --quiet shefvpn && ! ip link show ppp0"
style = "fg:3" # Yellow/Orange

[git_status]
windows_starship = '/mnt/c/Users/maffe/.cargo/bin/starship.exe'

[directory]
read_only = ' '
read_only_style = 'bold #f9c23c'

[zig]
symbol = '⚡️ '
version_format = 'v${major}.${minor}.${patch}'

[bun]
symbol = '🧄 '
style = 'bold yellow'

[golang]
symbol = ' '

[rust]
symbol = ' '

[java]
symbol = ' '
style = 'bold #f89917'

[gradle]
symbol = ' '

[ruby]
detect_variables = []

[container]
disabled = true

[netns]
disabled = true
