[font]
size = 12
normal = { family = "GeistMono Nerd Font", style = "Regular" }
bold = { family = "GeistMono Nerd Font", style = "Bold" }
italic = { family = "GeistMono Nerd Font", style = "Itailc" }
bold_italic = { family = "GeistMono Nerd Font", style = "Bold Itailc" }

[colors]
#cursor = { text = "#000000", cursor = "#0088CC" }
